version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
    - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    - ./frontend/build:/usr/share/nginx/html
    rstart: always
      
    # environment:
    #   - NODE_ENV=production

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     environment:
#       - DJANGO_SETTINGS_MODULE=backend.settings
#     depends_on:
#       - db

#   db:
#     image: postgres:14
#     restart: always
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB=fuzzymind
#       POSTGRES_USER=postgres
#       POSTGRES_PASSWORD=yourpassword

# volumes:
#   postgres_data:
